
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor   

metadata:
  name: shakachow-backend-monitor
  namespace: monitoring
 
  labels:
    app: shakachow-backend
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - shakachow
  selector:
    matchLabels:
      app: shakachow-backend
  endpoints:
    - port: http
      path: /api/health
      interval: 15s
      scrapeTimeout: 10s
