

apiVersion: v1
kind: Service

metadata:
  name: shakachow-frontend-svc


  namespace: shakachow

  labels:
    app: shakachow-frontend
    tier: frontend

spec:
  type: ClusterIP

  selector:
    app: shakachow-frontend


  ports:
    - name: http
      protocol: TCP
      port: 80

      targetPort: 80

