apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: shakachow
  labels:
    app: shakachow-backend
    component: config
data:
  NODE_ENV: "production"
  PORT: "5000"
  JWT_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"
  CLIENT_URL: "https://shakachow.engrshakacloud.online"
 